### ISSUE TITLE
Name for the package

### ISSUE THREAD

**Issue by musigma-admin** [Mu-Sigma/analysis-pipelines#13]
In GitLab by @Naren.Srinivasan on Aug 30, 2018, 14:59

* Decide on the name
* Update all function names, classes and documentation to reflect the same.

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Aug 31, 2018, 12:32

assigned to @Anoop.S

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Aug 31, 2018, 12:32

assigned to @Abhilash.J2 and unassigned @Anoop.S

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Aug 31, 2018, 12:32

unassigned @Abhilash.J2

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Aug 31, 2018, 12:37

@Vedavyas.C , @Abhilash.J2 , @Anoop.S - Would like your thoughts on this. Want a name which represents the objectives of the package but is different from "recipes" as there is a package of the same name by hadley.

**Comment by musigma-admin** [comment]
In GitLab by @Neeratyoy.Mallik on Aug 31, 2018, 14:25

"edaTree": EDA is included since it is about EDA. Tree, from a data structure POV, since it gives the notion of a flow of sorts

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Aug 31, 2018, 14:51

@Neeratyoy.Mallik - I want the package to be more than eda. Looking to add other brick functions as well. We also have support for spark jobs/ structured streaming now.

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Aug 31, 2018, 14:55

The main objectives of the package are:

- Create recipes/ flows/ pipelines which are reusable and can be put into production. Allow for repeated calling of these pipelines, in a batch context, or continuous processing in a streaming context

Couple of other names I thought of:

* "composer" - As analysts compose these analyses. The last "r" as a play on R. However, with this the putting into production as aspect does not come out.
* "pipeliner" - As analysts create analysis pipelines. Similar to the "recipe" construct but just different terminology. Could feed well into the idea of exporting as BPMN for example and deploying through a workflow orchestrator like muFlow.

I'm leaning towards "pipeliner" at the moment - as it seems to represent what we're looking to accomplish.

Thoughts?

**Comment by musigma-admin** [comment]
In GitLab by @Abhilash.J2 on Aug 31, 2018, 16:08

pipelineR seems good. Consistent with python sklearn's pipeline module. 

Some other convoluted ones could be with the 'rx' -- flowRx , dataRx ? muRx !(:))

or rxCreator

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Sep 3, 2018, 12:18

Haha, don't want the name linked with rX.

So I'm thinking pipeliner or pipelineR with the classes called 'AnalysisPipeline' and 'SparkAnalysisPipeline'

Am thinking if we can use pipeline-related verbs for the methods - Like 'plumb', or so on.

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Sep 3, 2018, 12:19

Just discovered that there is already a package of that name, which is extremely similar to the 'recipes' package.

Thinking 'analysisPipelines' instead.

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Sep 3, 2018, 15:26

changed the description

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Sep 3, 2018, 15:35

assigned to @Naren.Srinivasan

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Sep 5, 2018, 12:30

@Anoop.S @Abhilash.J2 @Vedavyas.C  - Any other thoughts? 

Thinking of finalizing 'analysisPipelines'

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Sep 6, 2018, 13:02

@Anoop.S @Abhilash.J2 @Vedavyas.C -  Finalizing 

> analysisPipelines 

as the working name for now.

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Sep 6, 2018, 14:13

This has been changed in function names, documentation, vignettes, RStudio project name. etc.

Also, the git project has been renamed. 

Will need to perform a new checkout by:

`git clone git@mugitlab.mu-sigma.com:eoc_foundation_wip/analysis-pipelines.git`

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Sep 6, 2018, 14:13

closed

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Sep 11, 2018, 22:07

reopened

**Comment by musigma-admin** [comment]
In GitLab by @Zubin.Dowlaty on Sep 12, 2018, 00:59

how about "chain link" or "chain linker"

**Comment by naren-srinivasan** [comment]
Closing this issue - Eventual decision was to go with 'analysisPipelines'
