### ISSUE TITLE
Final documentation review before CRAN release

### ISSUE THREAD

**Issue by musigma-admin** [Mu-Sigma/analysis-pipelines#15]
In GitLab by @Naren.Srinivasan on Sep 3, 2018, 15:21

* Add examples and authors for all functions

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Nov 9, 2018, 18:08

changed title from **{-Add examples for all functions-}** to **{+Final documentation review before CRAN release+}**

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Nov 9, 2018, 18:08

changed the description

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Nov 26, 2018, 20:34

mentioned in commit 42bdf8449b8c8df100bbe9724ed0b485ec5af1e2

**Comment by musigma-admin** [comment]
In GitLab by @Naren.Srinivasan on Nov 27, 2018, 20:24

mentioned in commit 8b3812e133cead55cf02213dbfa45bc05a63b45c

**Comment by naren-srinivasan** [comment]
Documentation has been updated, including resolution of CRAN check issues. Vignettes have also been updated and minor corrections made. Closing this issue
