### ISSUE TITLE
User-Defined Functions Not being saved

### ISSUE THREAD

**Issue by husamrahman** [Mu-Sigma/analysis-pipelines#49]
Do I have to register user-defined functions every time I open up a new R session to use them? Or am I registering the function incorrectly? Thanks!

**Comment by naren1991** [comment]
Functions once registered get saved to the registry which is active for that R Session. You can, however, save and load registries to use them across R sessions. When a registry is saved, all functions registered in that session are saved. Once a registry is loaded, all the functions in that registry now become accessible.

The functions are - `saveRegistry` & `loadRegistry`.

You can see an example in the main vignette - *Analysis pipelines for working with R data frames* - also linked [here](https://cran.r-project.org/web/packages/analysisPipelines/vignettes/Analysis_pipelines_for_working_with_R_dataframes.html#saving-and-loading-registries)

 Hope this helps.

**Comment by naren1991** [comment]
Closing this issue.
