### ISSUE TITLE
Feature Request: Be able to pass multiple outputs from previous steps into a list to be used in a another step

### ISSUE THREAD

**Issue by husamrahman** [Mu-Sigma/analysis-pipelines#52]
Feature Request: Have the ability to combine multiple outputs form previous steps and pass it as a list in the next.

For example: nextFunction( list( ~f1, ~f2, ~f3) where f1, f2, and f3 are outputs from previous steps.

**Comment by naren1991** [comment]
The recommended approach in such a case would be to pass the outputs as 3 different arguments. This allows for a cleaner implementation with lesser potential for bugs/ issues. Like so:

nextFunction(arg1 = ~f1, arg2 = ~f2, arg3 = ~f3)

**Comment by naren1991** [comment]
Closing this issue.
