### ISSUE TITLE
Resolve WARN issues in CRAN checks occurring due to the updated version of tibble (3.0.0 +)

### ISSUE THREAD

**Issue by naren1991** [Mu-Sigma/analysis-pipelines#58]
The updated version of tibble is causing issues with certain functionality in analysisPipelines, and errors in corresponding vignettes

**Comment by SangeetM** [comment]
More details regarding the issues caused can be found [here](https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcran.r-project.org%2Fweb%2Fchecks%2Fcheck_summary_by_maintainer.html&data=02%7C01%7CSangeet.Das%40Mu-Sigma.Com%7C850a16f1baa942e2bcdb08d7e13c6391%7C56794af129b14e4ba44715e6df4f649b%7C0%7C0%7C637225521790351084&sdata=t4KbmJO%2BssojdImTnPMcV3ltA%2F6TOaT5ZkXng2pAsoo%3D&reserved=0)

**Comment by naren1991** [comment]
This issue has been fixed. It was a minor issue due to the fact that in tibble 3.0.0+, automatic type coercions for columns are not done. There was 1 instance in the code where explicit conversion to the type of the column had to be done.
