### ISSUE TITLE
Vignette | Rebuilding  failed for some of the vignettes

### ISSUE THREAD

**Issue by SangeetM** [Mu-Sigma/analysis-pipelines#61]
Details of the failed vignette:

- Analysis_pipelines_for_working_with_R_dataframes.Rmd
- Meta_Pipelines.Rmd
![Screenshot from 2020-06-07 16-47-23](https://user-images.githubusercontent.com/9531507/83967403-95580080-a8de-11ea-8474-4ed3cf3d28d5.png)

**Comment by naren1991** [comment]
This may be a result of a new version of another package, which was the case in the previous time. I will look into this.

**Comment by SangeetM** [comment]
tried with **dplyr** 0.8.5 ... works ... received a mail from CRAN which says to fix this before 15th June to retain package in CRAN. A more detailed overview for your reference https://cran.r-project.org/web/checks/check_results_analysisPipelines.html
